version: '3'
services:
  web:
    container_name: halal-export     
    image: halal:1.0.0            
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"                           
